# Generated by Django 4.1.7 on 2023-02-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree_items",
                to="tree.treemenu",
            ),
        ),
        migrations.AlterField(
            model_name="treeitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childrens",
                to="tree.treeitem",
            ),
        ),
    ]
