# Generated by Django 4.1.7 on 2023-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree", "0003_alter_treeitem_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="treeitem",
            name="link",
            field=models.CharField(
                blank=True, editable=False, max_length=250, null=True
            ),
        ),
    ]
